### PR TITLE
Updated URL and hash for Project64 - fixes #19

### LINKED ISSUE #19: [project64] Project 64 package is broken

### PR DESCRIPTION
**Pull request by vikingtiger**
Updated the URL and hash for the Project64 2.3.2 binary. The hash had to be updated because it seems to be a slightly updated build.

### CODE REVIEW

**Comment by scowalt** [comment]
Apologies for the late response to this! My GitHub notification settings are not set up properly.

**Comment by scowalt** [comment]
@vikingtiger Packages with a given id and version cannot be modified. To upload a new package for this version, we'll need to change the "version" to something else. Common practice here is to append the date the package was updated. So let's change the version from "2.3.2" to "2.3.2.20190217"

**Comment by vikingtiger** [comment]
I apologize. It makes sense that the combination of package id and version should be unique. I have committed an update to the .nuspec making the proposed change.

**Comment by scowalt** [comment]
Started chocolatey approval process: https://chocolatey.org/packages/project64/2.3.2.20190217

If they sign off I'll merge this in,
Otherwise I'll report back with potentially more changes that are required.

**Comment by scowalt** [comment]
Thanks for the contribution @vikingtiger!

**Pull request merged**
